version: '3.8'

services:
  # Backend API service
  backend:
    image: ghcr.io/csyyysc/image-processing-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    volumes:
      - image-processing-data:/app/data
      - image-processing-uploads:/app/uploads
      - image-processing-logs:/app/logs
    command: ["uv", "run", "python", "-m", "uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend service
  frontend:
    image: ghcr.io/csyyysc/image-processing-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    env_file:
      - .env.prod
    depends_on:
      backend:
        condition: service_healthy
    command: ["uv", "run", "streamlit", "run", "frontend/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    restart: unless-stopped

volumes:
  image-processing-data:
  image-processing-uploads:
  image-processing-logs:
